#!/usr/bin/env bash
# generate_secrets.sh
# Xcode Run Script Phase: reads .env from project root and emits
# DayPage/Config/GeneratedSecrets.swift as enum Secrets static constants.
#
# Usage (Xcode Run Script Phase, before Compile Sources):
#   "${SRCROOT}/scripts/generate_secrets.sh"
#
# Input:  ${SRCROOT}/.env
# Output: ${SRCROOT}/DayPage/Config/GeneratedSecrets.swift

set -euo pipefail

ENV_FILE="${SRCROOT}/.env"
OUTPUT_FILE="${SRCROOT}/DayPage/Config/GeneratedSecrets.swift"

# If .env doesn't exist and GeneratedSecrets.swift already has values, skip regeneration.
# This preserves secrets during Archive/TestFlight builds where .env is not present.
if [[ ! -f "${ENV_FILE}" ]]; then
    if [[ -f "${OUTPUT_FILE}" ]] && grep -q 'supabaseURL: String = "https://' "${OUTPUT_FILE}"; then
        echo "[generate_secrets] .env not found, keeping existing ${OUTPUT_FILE}"
        exit 0
    else
        echo "[generate_secrets] ERROR: .env not found and ${OUTPUT_FILE} has no valid secrets. Add .env to \${SRCROOT}." >&2
        exit 1
    fi
fi

# ── Helper ──────────────────────────────────────────────────────────────────
read_env_value() {
    local key="$1"
    local value=""
    # Strip comments, blank lines; match KEY=VALUE (no spaces around =)
    value=$(grep -E "^${key}=" "${ENV_FILE}" | head -1 | cut -d'=' -f2- | tr -d '\r')
    # Escape backslash and double-quote for Swift string literal
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    echo "${value}"
}

# ── Read values ──────────────────────────────────────────────────────────────
OPENAI_CHAT_API_KEY=$(read_env_value "OPENAI_CHAT_API_KEY")
OPENAI_CHAT_BASE_URL=$(read_env_value "OPENAI_CHAT_BASE_URL")
OPENAI_CHAT_MODEL=$(read_env_value "OPENAI_CHAT_MODEL")
OPENAI_WHISPER_API_KEY=$(read_env_value "OPENAI_WHISPER_API_KEY")
OPENWEATHER_API_KEY=$(read_env_value "OPENWEATHER_API_KEY")
SUPABASE_URL=$(read_env_value "SUPABASE_URL")
SUPABASE_ANON_KEY=$(read_env_value "SUPABASE_ANON_KEY")
SENTRY_DSN=$(read_env_value "SENTRY_DSN")

# ── Emit Swift file ──────────────────────────────────────────────────────────
mkdir -p "$(dirname "${OUTPUT_FILE}")"

cat > "${OUTPUT_FILE}" << SWIFT
// GeneratedSecrets.swift — AUTO-GENERATED by Scripts/generate_secrets.sh
// DO NOT EDIT MANUALLY. DO NOT COMMIT (see .gitignore).
// Regenerated on every build from the project-root .env file.

enum Secrets {
    static let openAIChatApiKey: String = "${OPENAI_CHAT_API_KEY}"
    static let openAIChatBaseURL: String = "${OPENAI_CHAT_BASE_URL}"
    static let openAIChatModel: String = "${OPENAI_CHAT_MODEL}"
    static let openAIWhisperApiKey: String = "${OPENAI_WHISPER_API_KEY}"
    static let openWeatherApiKey: String = "${OPENWEATHER_API_KEY}"
    static let supabaseURL: String = "${SUPABASE_URL}"
    static let supabaseAnonKey: String = "${SUPABASE_ANON_KEY}"
    static let sentryDSN: String = "${SENTRY_DSN}"
}
SWIFT

echo "[generate_secrets] wrote ${OUTPUT_FILE}"
