#!/usr/bin/env bash
# generate_secrets.sh
# Xcode Run Script Phase: reads .env from project root and emits
# DayPage/Config/GeneratedSecrets.swift as enum Secrets static constants.
#
# Usage (Xcode Run Script Phase, before Compile Sources):
#   "${SRCROOT}/scripts/generate_secrets.sh"
#
# Input:  ${SRCROOT}/.env
# Output: ${SRCROOT}/DayPage/Config/GeneratedSecrets.swift

set -euo pipefail

ENV_FILE="${SRCROOT}/.env"
OUTPUT_FILE="${SRCROOT}/DayPage/Config/GeneratedSecrets.swift"

# ── Helper ──────────────────────────────────────────────────────────────────
read_env_value() {
    local key="$1"
    local value=""
    if [[ -f "${ENV_FILE}" ]]; then
        # Strip comments, blank lines; match KEY=VALUE (no spaces around =)
        value=$(grep -E "^${key}=" "${ENV_FILE}" | head -1 | cut -d'=' -f2- | tr -d '\r')
    fi
    # Escape backslash and double-quote for Swift string literal
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    echo "${value}"
}

# ── Read values ──────────────────────────────────────────────────────────────
DASHSCOPE_API_KEY=$(read_env_value "DASHSCOPE_API_KEY")
DASHSCOPE_BASE_URL=$(read_env_value "DASHSCOPE_BASE_URL")
DASHSCOPE_MODEL=$(read_env_value "DASHSCOPE_MODEL")
OPENAI_WHISPER_API_KEY=$(read_env_value "OPENAI_WHISPER_API_KEY")
OPENWEATHER_API_KEY=$(read_env_value "OPENWEATHER_API_KEY")

# ── Emit Swift file ──────────────────────────────────────────────────────────
mkdir -p "$(dirname "${OUTPUT_FILE}")"

cat > "${OUTPUT_FILE}" << SWIFT
// GeneratedSecrets.swift — AUTO-GENERATED by Scripts/generate_secrets.sh
// DO NOT EDIT MANUALLY. DO NOT COMMIT (see .gitignore).
// Regenerated on every build from the project-root .env file.

enum Secrets {
    static let dashScopeApiKey: String = "${DASHSCOPE_API_KEY}"
    static let dashScopeBaseURL: String = "${DASHSCOPE_BASE_URL}"
    static let dashScopeModel: String = "${DASHSCOPE_MODEL}"
    static let openAIWhisperApiKey: String = "${OPENAI_WHISPER_API_KEY}"
    static let openWeatherApiKey: String = "${OPENWEATHER_API_KEY}"
}
SWIFT

echo "[generate_secrets] wrote ${OUTPUT_FILE}"
