#!/usr/bin/env node
// Generates the :root { ... } /* @tokens */ block in web/src/app/globals.css from tokens.json.
// Run: node --experimental-strip-types design-tokens/generators/to-css.ts

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

type Tokens = {
  version: string;
  colors: Record<string, string>;
  fonts: Record<string, string>;
  fontSize: Record<string, number>;
  radii: Record<string, number>;
  shadows: Record<string, string>;
  elevation: Record<string, string>;
  spacing: Record<string, number>;
  motion: Record<string, string | number>;
  gestures?: Record<string, number>;
  dark: {
    colors: Record<string, string>;
    elevation: Record<string, string>;
  };
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..");
const TOKENS_PATH = join(ROOT, "design-tokens", "tokens.json");
const CSS_PATH = join(ROOT, "web", "src", "app", "globals.css");

const BEGIN_MARK = "/* @tokens:begin auto-generated by design-tokens/generators/to-css.ts */";
const END_MARK = "/* @tokens:end */";

function buildBlock(t: Tokens): string {
  const lines: string[] = [];
  lines.push(BEGIN_MARK);
  lines.push(`/* DayPage v${t.version} design tokens — DO NOT EDIT by hand. Edit design-tokens/tokens.json and run \`pnpm tokens:build\`. */`);
  lines.push(":root {");

  lines.push("  /* Colors */");
  for (const [k, v] of Object.entries(t.colors)) {
    lines.push(`  --${k}: ${v};`);
  }

  lines.push("");
  lines.push("  /* Font families (postscript names; consumers wrap in var()/fallbacks) */");
  for (const [k, v] of Object.entries(t.fonts)) {
    lines.push(`  --font-family-${k}: "${v}";`);
  }

  lines.push("");
  lines.push("  /* Font sizes (px) */");
  for (const [k, v] of Object.entries(t.fontSize)) {
    lines.push(`  --font-size-${k}: ${v}px;`);
  }

  lines.push("");
  lines.push("  /* Radii (px; pill=9999) */");
  for (const [k, v] of Object.entries(t.radii)) {
    lines.push(`  --radius-${k}: ${v}px;`);
  }

  lines.push("");
  lines.push("  /* Shadows (legacy — prefer --elev-* for new code) */");
  for (const [k, v] of Object.entries(t.shadows)) {
    lines.push(`  --shadow-${k}: ${v};`);
  }

  lines.push("");
  lines.push("  /* Elevation (v9 — three-tier: flat, raise, float) */");
  for (const [k, v] of Object.entries(t.elevation)) {
    lines.push(`  --elev-${k}: ${v};`);
  }

  lines.push("");
  lines.push("  /* Spacing (px) */");
  for (const [k, v] of Object.entries(t.spacing)) {
    lines.push(`  --space-${k}: ${v}px;`);
  }

  lines.push("");
  lines.push("  /* Motion */");
  for (const [k, v] of Object.entries(t.motion)) {
    if (typeof v === "number") {
      lines.push(`  --motion-${k}: ${v}ms;`);
    } else {
      lines.push(`  --motion-${k}: ${v};`);
    }
  }

  if (t.gestures && Object.keys(t.gestures).length > 0) {
    lines.push("");
    lines.push("  /* Gestures */");
    for (const [k, v] of Object.entries(t.gestures)) {
      lines.push(`  --gesture-${k}: ${v};`);
    }
  }

  lines.push("}");

  // Dark mode — overrides colors + elevation only; everything else
  // (radii, fonts, motion, gestures) stays identical to :root.
  //
  // Selector convention: `[data-theme="dark"]` (explicit user opt-in) plus
  // `[data-theme="system"]` inside `prefers-color-scheme: dark` (follow OS).
  // This matches DayPage's existing three-state ThemeProvider (light / dark /
  // system) — a plain `.dark` class can't express the "follow OS" state.
  //
  // Emitted twice with identical variable bodies via a shared helper.
  const darkBody: string[] = [];
  for (const [k, v] of Object.entries(t.dark.colors)) {
    darkBody.push(`    --${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(t.dark.elevation)) {
    darkBody.push(`    --elev-${k}: ${v};`);
  }

  lines.push("");
  lines.push("/* Dark mode — explicit user opt-in via <html data-theme=\"dark\"> */");
  lines.push('[data-theme="dark"] {');
  lines.push(...darkBody);
  lines.push("}");

  lines.push("");
  lines.push("/* Dark mode — follow OS when <html data-theme=\"system\"> */");
  lines.push("@media (prefers-color-scheme: dark) {");
  lines.push('  [data-theme="system"] {');
  lines.push(...darkBody);
  lines.push("  }");
  lines.push("}");

  lines.push(END_MARK);
  return lines.join("\n");
}

function main() {
  const tokens: Tokens = JSON.parse(readFileSync(TOKENS_PATH, "utf8"));
  const block = buildBlock(tokens);

  const css = readFileSync(CSS_PATH, "utf8");
  const beginIdx = css.indexOf(BEGIN_MARK);
  const endIdx = css.indexOf(END_MARK);

  let out: string;
  if (beginIdx >= 0 && endIdx > beginIdx) {
    out = css.slice(0, beginIdx) + block + css.slice(endIdx + END_MARK.length);
  } else {
    // First-time injection: prepend after the first @import line (or at top).
    const importMatch = css.match(/^@import[^\n]*\n/);
    if (importMatch) {
      const insertAt = importMatch[0].length;
      out = css.slice(0, insertAt) + "\n" + block + "\n" + css.slice(insertAt);
    } else {
      out = block + "\n\n" + css;
    }
  }

  if (out !== css) {
    writeFileSync(CSS_PATH, out);
    console.log(`[tokens] wrote ${CSS_PATH}`);
  } else {
    console.log(`[tokens] ${CSS_PATH} already up to date`);
  }
}

main();
